namespace TLCGen.Generators.Shared
{
    public enum CCOLCodeTypeEnum
    {
        // REB - TRAFFICK
        RebCBeforeIncludes,
        RebCIncludes,
        RebCTop,
        RebCInitApplication,
        RebCKlokBehandeling,
        RebCGroentijden,
        RebCAanvragen,
        RebCVerlengen,
        RebCMeeverlengGroen,
        RebCVeiligheidsGroen,
        RebCPostApplication,
        RebCSystemApplication,
        RebCDumpApplication,
        RebCSpecialSignals,

		// REG
        RegCBeforeIncludes,
        RegCIncludes,
        RegCTop,
        RegCKwcApplication,
        RegCPreApplication,
        RegCKlokPerioden,
        RegCAanvragen,
        RegCRealisatieTijden,
        RegCVerlenggroen,
        RegCMaxgroen,
        RegCMaxgroenNaAdd,
        RegCWachtgroen,
        RegCMeetkriterium,
        RegCFileVerwerking,
        RegCDetectieStoring,
        RegCMeeverlengen,
        RegCRealisatieAfhandelingVoorModules,
        RegCRealisatieAfhandelingModules,
        RegCRealisatieAfhandelingNaModules,
        RegCRealisatieAfhandeling,
        RegCAlternatieven,
        RegCSynchronisaties,
        RegCInitApplication,
        RegCApplication,
        RegCPostApplication,
        RegCPreSystemApplication,
        RegCSystemApplication,
        RegCSystemApplication2,
        RegCPostSystemApplication,
        RegCDumpApplication,
        RegCSpecialSignals,

        // PRIO
        PrioCIncludes,
        PrioCTop,
        PrioCInitPrio,
        PrioCInstellingen,
        PrioCRijTijdScenario,
        PrioCInUitMelden,
        PrioCOnderMaximum,
        PrioCAfkapGroen,
        PrioCStartGroenMomenten,
        PrioCAfkappen,
        PrioCTerugkomGroen,
        PrioCGroenVasthouden,
        PrioCMeetkriterium,
        PrioCPrioriteitsOpties,
        PrioCPrioriteitsNiveau,
        PrioCPrioriteitsToekenning,
        PrioCTegenhoudenConflicten,
        PrioCPostAfhandelingPrio,
        PrioCPARCorrecties,
        PrioCPARCcol,
        PrioCSpecialSignals,
        PrioCBottom,

        // TAB
        TabCBeforeIncludes,
	    TabCIncludes,
        TabCControlDefaults,
	    TabCControlParameters,

        // SYS
        SysHBeforeUserDefines,

        // HST
        HstCTop,
        HstCPostInitApplication,
		HstCPreApplication,
		HstCKlokPerioden,
		HstCAanvragen,
		HstCVerlenggroen,
		HstCMaxgroen,
		HstCWachtgroen,
		HstCMeetkriterium,
		HstCDetectieStoring,
		HstCMeeverlengen,
		HstCSynchronisaties,
		HstCAlternatief,
		HstCRealisatieAfhandeling,
		HstCPostApplication,
		HstCPreSystemApplication,
		HstCPostSystemApplication,
		HstCPostDumpApplication,
        HstCPrioHalfstarSettings,
    };
}
